### PR TITLE
Checking if YT is undefined

### PR DESCRIPTION
**Pull request by JuhQ**
I was getting "YT is undefined" error so changed the check a bit.

### CODE REVIEW

**Comment by brandly** [comment]
thanks for the PR!

any situation in which the `if (typeof YT === "undefined")` comparison passes, the `if (!YT)` should also pass, so i don't understand how this affects anything

could you give more details about the error you were running into?

**Comment by JuhQ** [comment]
Using async attribute in script tag sometimes gave "Undefined variable" error, especially when internets was lagging.

`<script src="https://www.youtube.com/iframe_api" async></script>`

Basically if you run `!YT` in console, you'll see the same effect. Running `typeof YT === "undefined"` will return true.

screen shot 2015-04-29 at 22 40 54

**Comment by brandly** [comment]
ohhhh of course. that makes sense. thanks!

**Comment by brandly** [comment]
[v1.0.1](https://github.com/brandly/angular-youtube-embed/releases/tag/v1.0.1), thanks again :star2:

**Pull request merged**
